language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-26.0.0

    # The SDK version used to compile your project
    - android-25

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
  - yes | sdkmanager "platforms;android-26"
  - yes | sdkmanager "build-tools;27.0.3"
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
install:
  - chmod +x ./gradlew
jobs:
  include:
    - stage: test
      script: ./gradlew clean test -PexcludeModule=java-se
    - stage: assemble
      if: branch != master
      script: ./gradlew clean assemble
    - stage: upload
      if: branch = master
      script: ./gradlew clean assemble bintrayUpload 
