#!/bin/bash
./gradlew publishAndroid-glidePublicationToMavenRepository
echo wait
sleep 300
./gradlew publishAndroidPublicationToMavenRepository
echo wait
sleep 300
./gradlew publishBasePublicationToMavenRepository
echo wait
sleep 300
./gradlew publishCryptoPublicationToMavenRepository
echo wait
sleep 300
./gradlew publishFilePublicationToMavenRepository
echo wait
sleep 300
./gradlew publishHttp-apachePublicationToMavenRepository
echo wait
sleep 300
./gradlew publishHttpPublicationToMavenRepository
echo wait
sleep 300
./gradlew publishJavasePublicationToMavenRepository
echo wait
sleep 300
./gradlew publishPathPublicationToMavenRepository
echo wait
sleep 300
./gradlew publishZipPublicationToMavenRepository
echo Complete.
